const express = require('express');
const router = express.Router();
const { protect, restrictTo } = require('../middlewares/auth.middleware');
const membership = require('../controllers/membership.controller');
router.get('/plans', membership.plans);
router.get('/current', protect, membership.current);
router.post('/checkout', protect, membership.checkout);
router.get('/payments/history', protect, membership.history);
router.get('/admin/payments', protect, restrictTo('ADMIN'), membership.adminList);
router.patch('/admin/payments/:id/verify', protect, restrictTo('ADMIN'), membership.adminVerify);
module.exports = router;
