import { useEffect, useState } from 'react'
import { AdminService } from '@/services/admin.api'
import { formatVND } from '@/utils/format'
const statuses = ['PENDING','CONFIRMED','SHIPPING','DELIVERED','CANCELLED']
export function AdminOrdersPage() {
 const [items,setItems]=useState<any[]>([]); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true)
 const load=()=>{setLoading(true);AdminService.orders({search,status:status||undefined}).then(r=>setItems(r.data.data.orders)).catch(e=>setError(e.response?.data?.message||'Could not load orders.')).finally(()=>setLoading(false))}; useEffect(()=>{load()},[search,status])
 const change=async(id:string,value:string)=>{try{await AdminService.updateOrder(id,value);load()}catch(e:any){setError(e.response?.data?.message||'Could not update order status.')}}
 return <section><h1 className="font-heading text-3xl font-bold">Orders</h1><div className="my-6 flex gap-3"><input aria-label="Search orders" placeholder="Order ID, customer or email" value={search} onChange={e=>setSearch(e.target.value)} className="rounded-lg border px-3 py-2"/><select aria-label="Filter order status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border px-3 py-2"><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>{error&&<p role="alert" className="mb-3 text-red-600">{error}</p>}{loading?<p>Loading orders…</p>:items.length===0?<p className="rounded-xl border p-8 text-center">No orders found.</p>:<div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{['Order','Customer','Email','Total','Status','Created'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{items.map(o=><tr key={o._id} className="border-t"><td className="p-3">{o._id.slice(-8)}</td><td className="p-3">{o.userId?.fullName||o.shippingAddress?.fullName||'—'}</td><td className="p-3">{o.userId?.email||'—'}</td><td className="p-3">{formatVND(o.totalPrice)}</td><td className="p-3"><select aria-label={`Status ${o._id}`} value={o.status} onChange={e=>change(o._id,e.target.value)} className="rounded border p-1">{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td className="p-3">{new Date(o.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section>
}
