import { useCallback, useEffect, useState } from 'react'
import { MembershipService } from '@/services/membership.api'
import { formatVND } from '@/utils/format'
type Row = { _id: string; paymentReference: string; amount: number; paymentMethod: string; status: string; createdAt: string; userId: { fullName: string; email: string }; membershipPlanId: { name: string; code: string } }
export function AdminMembershipPaymentsPage() {
  const [rows,setRows]=useState<Row[]>([]); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState('')
  const load=useCallback(()=>MembershipService.adminPayments(status).then((r)=>setRows(r.data.data.payments)).catch(()=>setError('Không thể tải thanh toán Membership.')),[status])
  useEffect(()=>{load()},[load])
  const decide=async(row:Row,action:'verify'|'reject')=>{const reason=action==='reject'?window.prompt('Lý do từ chối (tùy chọn):'):undefined;if(action==='reject'&&reason===null)return;setBusy(row._id);setError('');try{await MembershipService.verifyBank(row._id,action,reason||undefined);await load()}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||'Không thể cập nhật giao dịch.')}finally{setBusy('')}}
  return <section><h1 className="font-heading text-3xl font-bold">Membership Payments</h1><select aria-label="Filter status" className="my-5 rounded-lg border p-2" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{['PENDING','SUCCESS','FAILED','CANCELLED','EXPIRED'].map((s)=><option key={s}>{s}</option>)}</select>{error&&<p role="alert" className="mb-3 text-red-700">{error}</p>}<div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{['Mã thanh toán','Khách hàng','Gói','Số tiền','Phương thức','Trạng thái','Ngày tạo','Thao tác'].map((x)=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row)=><tr className="border-t" key={row._id}><td className="p-3">{row.paymentReference}</td><td className="p-3">{row.userId?.fullName}<br/>{row.userId?.email}</td><td className="p-3">{row.membershipPlanId?.name}</td><td className="p-3">{formatVND(row.amount)}</td><td className="p-3">{row.paymentMethod}</td><td className="p-3">{row.status}</td><td className="p-3">{new Date(row.createdAt).toLocaleDateString('vi-VN')}</td><td className="p-3">{row.paymentMethod==='BANK_TRANSFER'&&row.status==='PENDING'&&<div className="flex gap-2"><button disabled={busy===row._id} onClick={()=>decide(row,'verify')} className="rounded bg-green-700 px-2 py-1 text-white disabled:opacity-50">Xác minh</button><button disabled={busy===row._id} onClick={()=>decide(row,'reject')} className="rounded bg-red-700 px-2 py-1 text-white disabled:opacity-50">Từ chối</button></div>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-center text-gray-500">Không có giao dịch.</p>}</div></section>
}
