import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { MembershipService, type MembershipPlan } from '@/services/membership.api'
import { useAuthStore } from '@/store/authStore'
import { Button } from '@/components/ui/Button'
import { formatVND } from '@/utils/format'

const methods = [{ id: 'VNPAY', label: 'Thẻ quốc tế / VNPay' }, { id: 'MOMO', label: 'Ví điện tử MoMo' }, { id: 'BANK_TRANSFER', label: 'Chuyển khoản ngân hàng' }] as const
export function MembershipCheckoutPage() {
  const [search] = useSearchParams(); const navigate = useNavigate(); const user = useAuthStore((s) => s.user)
  const [plans, setPlans] = useState<MembershipPlan[]>([]); const [code, setCode] = useState(search.get('plan') || 'PREMIUM'); const [method, setMethod] = useState<typeof methods[number]['id']>('VNPAY'); const [fullName, setFullName] = useState(user?.fullName || ''); const [email, setEmail] = useState(user?.email || ''); const [phone, setPhone] = useState(user?.phone || ''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const selected = useMemo(() => plans.find((p) => p.code === code), [plans, code])
  useEffect(() => { MembershipService.plans().then((r) => setPlans(r.data.data.plans)).catch(() => setError('Không thể tải danh sách gói.')) }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setBusy(true); setError(''); try { const response = await MembershipService.checkout({ planCode: selected.code, paymentMethod: method, fullName, email, phone }); const data = response.data.data; if (data.free) { navigate('/membership'); return } if (data.paymentUrl) { window.location.assign(data.paymentUrl); return } navigate(`/payment/pending?reference=${encodeURIComponent(data.paymentReference || '')}`, { state: data.transfer }) } catch (e) { setError((e as { response?: { data?: { message?: string } } }).response?.data?.message || 'Không thể tạo giao dịch. Vui lòng thử lại.') } finally { setBusy(false) } }
  return <form onSubmit={submit} className="mx-auto grid max-w-6xl gap-8 px-5 py-10 lg:grid-cols-[1.5fr_1fr]"><div className="space-y-8"><header><Link to="/membership" className="text-sm text-cyan-800">← Membership</Link><h1 className="mt-3 text-3xl font-bold">Membership Checkout</h1><p className="mt-2 text-gray-600">Chu kỳ thanh toán: Theo tháng</p></header><section><h2 className="mb-4 text-lg font-bold">Chọn gói thành viên</h2><div className="grid gap-3 sm:grid-cols-3">{plans.map((plan) => <button type="button" key={plan._id} onClick={() => setCode(plan.code)} className={`rounded-xl border p-4 text-left ${code === plan.code ? 'border-cyan-600 ring-1 ring-cyan-600' : 'border-gray-200'}`}><b>{plan.name}</b><p className="mt-2 text-sm">{plan.price ? `${formatVND(plan.price)} / tháng` : 'Miễn phí'}</p></button>)}</div></section><section><h2 className="mb-4 text-lg font-bold">Thông tin định danh</h2><div className="grid gap-4 sm:grid-cols-2">{[['Họ và tên',fullName,setFullName],['Email',email,setEmail],['Số điện thoại',phone,setPhone]].map(([label,value,setter]) => <label key={String(label)} className="text-sm">{String(label)} *<input required type={label==='Email'?'email':'text'} value={String(value)} onChange={(e) => (setter as (v:string)=>void)(e.target.value)} className="mt-1 w-full rounded-lg border p-3"/></label>)}</div></section>{Boolean(selected?.price) && <section><h2 className="mb-4 text-lg font-bold">Phương thức thanh toán</h2><div className="grid gap-3 sm:grid-cols-3">{methods.map((m) => <button type="button" key={m.id} onClick={() => setMethod(m.id)} className={`rounded-xl border p-4 text-left text-sm ${method === m.id ? 'border-cyan-600 ring-1 ring-cyan-600' : 'border-gray-200'}`}>{m.label}</button>)}</div></section>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}</div><aside className="h-fit rounded-2xl border p-6 lg:sticky lg:top-24"><h2 className="text-lg font-bold">Tổng kết đơn hàng</h2>{selected && <><h3 className="mt-6 text-xl font-bold">{selected.name}</h3><p className="mt-1 text-gray-600">{selected.price ? `${formatVND(selected.price)} / tháng` : 'Miễn phí'}</p><ul className="my-5 space-y-2 text-sm">{selected.features.map((f) => <li key={f}>✓ {f}</li>)}</ul><p className="border-t py-3 text-sm">Ngày bắt đầu: {new Date().toLocaleDateString('vi-VN')}<br/>Ngày hết hạn: {selected.billingCycle === 'FREE' ? 'Không thời hạn' : new Date(new Date().setMonth(new Date().getMonth()+1)).toLocaleDateString('vi-VN')}</p><div className="flex justify-between border-t py-4 font-bold"><span>Tổng thanh toán</span><span>{formatVND(selected.price)}</span></div></>}<Button type="submit" loading={busy} className="w-full" disabled={!selected}>{selected?.price ? 'Thanh toán ngay' : 'Kích hoạt gói miễn phí'}</Button></aside></form>
}
