import { useEffect, useState } from 'react'
import { Link, useLocation, useSearchParams } from 'react-router-dom'
import { CheckCircle2, Clock3, XCircle } from 'lucide-react'
import { MembershipService } from '@/services/membership.api'
import { formatVND } from '@/utils/format'
import { Button } from '@/components/ui/Button'

type Data = { order: { status: string; amount: number; paymentMethod: string; paidAt: string | null; paymentReference: string; membershipPlanId: { name: string } }; payment: { paymentStatus: string; transactionId: string | null }; membership: { membershipStatus: string } }
export function PaymentStatusPage({ view }: { view: 'success' | 'failed' | 'pending' }) {
  const [params] = useSearchParams(); const location = useLocation(); const reference = params.get('reference'); const transfer = location.state as { bankName?: string; accountNumber?: string; accountName?: string; amount?: number; paymentContent?: string; qrCodeUrl?: string } | null; const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(Boolean(reference)); const [error, setError] = useState('')
  useEffect(() => { if (!reference) return; let live = true; const load = () => MembershipService.result(reference).then((r) => { if (live) setData(r.data.data as Data) }).catch(() => { if (live) setError('Không tìm thấy giao dịch hoặc bạn không có quyền xem giao dịch này.') }).finally(() => { if (live) setLoading(false) }); load(); if (view === 'pending') { const timer = window.setInterval(load, 8000); return () => { live = false; clearInterval(timer) } } return () => { live = false } }, [reference, view])
  const confirmed = data?.payment.paymentStatus === 'SUCCESS' || data?.payment.paymentStatus === 'PAID'
  const title = view === 'success' ? 'THANH TOÁN THÀNH CÔNG' : view === 'failed' ? 'THANH TOÁN KHÔNG THÀNH CÔNG' : 'ĐANG CHỜ XÁC NHẬN THANH TOÁN'
  if (view === 'success' && (!reference || loading || !confirmed) && params.get('free') !== '1') return <div className="mx-auto max-w-xl px-5 py-20 text-center"><h1 className="text-2xl font-bold">{loading ? 'Đang xác minh giao dịch…' : 'Chưa xác nhận thanh toán'}</h1><p className="mt-3 text-gray-600">Membership chỉ được kích hoạt sau khi backend xác nhận giao dịch.</p>{error && <p role="alert" className="mt-3 text-red-700">{error}</p>}<Button asChild className="mt-6"><Link to="/membership">Quay lại Membership</Link></Button></div>
  const liveView = view === 'pending' && confirmed ? 'success' : view === 'pending' && ['FAILED','EXPIRED','CANCELLED'].includes(data?.payment.paymentStatus || '') ? 'failed' : view
  const liveTitle = liveView === 'success' ? 'THANH TOÁN THÀNH CÔNG' : liveView === 'failed' ? 'THANH TOÁN KHÔNG THÀNH CÔNG' : title
  const icon = liveView === 'success' ? <CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/> : liveView === 'failed' ? <XCircle className="mx-auto h-14 w-14 text-red-600"/> : <Clock3 className="mx-auto h-14 w-14 text-amber-600"/>
  return <section className="mx-auto max-w-xl px-5 py-16 text-center">{icon}<h1 className="mt-5 text-2xl font-bold">{liveTitle}</h1><p className="mt-3 text-gray-600">{liveView === 'pending' ? 'Membership sẽ được kích hoạt sau khi giao dịch được xác minh.' : liveView === 'failed' ? 'Giao dịch thất bại, bị hủy hoặc không xác minh được.' : 'Cảm ơn bạn đã đăng ký ALТERA.'}</p>{loading && <p className="mt-4">Đang tải trạng thái giao dịch…</p>}{view === 'pending' && transfer && !confirmed && <div className="mx-auto mt-6 max-w-sm rounded-xl border p-5 text-left text-sm">{transfer.qrCodeUrl && <img src={transfer.qrCodeUrl} alt="Mã QR chuyển khoản" className="mx-auto mb-4 max-h-56"/>}<p>Ngân hàng: <b>{transfer.bankName}</b></p><p className="mt-2">Số tài khoản: <b>{transfer.accountNumber}</b></p><p className="mt-2">Chủ tài khoản: <b>{transfer.accountName}</b></p><p className="mt-2">Số tiền: <b>{formatVND(transfer.amount || 0)}</b></p><p className="mt-2">Nội dung: <b>{transfer.paymentContent}</b></p><p className="mt-4 border-t pt-3 text-gray-600">Nếu bạn đã chuyển khoản, trạng thái sẽ cập nhật tự động sau khi được xác minh.</p></div>}{data && <div className="mt-7 rounded-xl border p-5 text-left text-sm"><p>Gói: <b>{data.order.membershipPlanId?.name || 'BASIC'}</b></p><p className="mt-2">Số tiền: <b>{formatVND(data.order.amount)}</b></p><p className="mt-2">Phương thức: {data.order.paymentMethod}</p><p className="mt-2">Mã giao dịch: {data.payment.transactionId || data.order.paymentReference}</p><p className="mt-2">Membership: {confirmed ? data.membership.membershipStatus : 'Chưa kích hoạt'}</p></div>}{error && <p role="alert" className="mt-3 text-red-700">{error}</p>}<div className="mt-7 flex justify-center gap-3"><Button asChild variant="outline"><Link to="/membership">{liveView === 'failed' ? 'Thử lại' : 'Xem Membership'}</Link></Button><Button asChild><Link to="/">Quay về ALTERA</Link></Button></div></section>
}
