import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import api from '@/utils/axios'
import { useAuthStore } from '@/store/authStore'
import { Trash2 } from 'lucide-react'
import { toast } from 'sonner'
type Profile={_id:string;username:string;displayName:string;bio?:string;avatar?:string;coverImage?:string}
type Design={_id:string;slug:string;name:string;thumbnail:string;price:number;status:string;category:string;collectionId?:string|null;rejectionReason?:string;likesCount:number;isLiked:boolean}
type Collection={_id:string;name:string}
type Data={profile:Profile;designs:Design[];collections:Collection[];followersCount:number;followingCount:number;isFollowing:boolean;owner:boolean;pagination:{page:number;totalPages:number;total:number}}
type Summary={totalDesigns:number;publishedDesigns:number;totalSales:number;grossSales:number;platformFee:number|null;designerEarnings:number|null;commissionConfigured:boolean}
const statusList=['PUBLISHED','DRAFT','PENDING_REVIEW','REJECTED','ARCHIVED']
export function DesignerProfilePage(){
 const {username=''}=useParams(),navigate=useNavigate(),user=useAuthStore(s=>s.user)
 const [data,setData]=useState<Data|null>(null),[summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState('')
 const [search,setSearch]=useState(''),[sort,setSort]=useState('Newest'),[collection,setCollection]=useState(''),[status,setStatus]=useState('PUBLISHED'),[category,setCategory]=useState(''),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[page,setPage]=useState(1)
 const [editOpen,setEditOpen]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState({username:'',displayName:'',bio:'',avatar:'',coverImage:''})
 const load=async()=>{try{const params={search,sort,page,limit:16,...(collection?{collection}:{}),...(category?{category}:{}),...(minPrice?{minPrice}:{}),...(maxPrice?{maxPrice}:{}),...(status!=='PUBLISHED'?{status}:{})};const r=await api.get<{data:Data}>('/designers/'+username,{params});setData(r.data.data)}catch{setError('Không tìm thấy nhà thiết kế.')}}
 useEffect(()=>{setData(null);setError('');void load()},[username,search,sort,collection,status,category,minPrice,maxPrice,page])
 useEffect(()=>{if(data?.owner)void api.get<{data:Summary}>('/designers/me/summary').then(r=>setSummary(r.data.data)).catch(()=>setSummary(null))},[data?.owner])
 const save=async()=>{setBusy(true);try{const r=await api.patch<{data:{profile:Profile}}>('/designers/me/profile',form);setEditOpen(false);if(r.data.data.profile.username!==username)navigate('/designer/'+r.data.data.profile.username,{replace:true});else await load()}catch(e:any){setError(e?.response?.data?.message||'Không thể cập nhật hồ sơ.')}finally{setBusy(false)}}
 const follow=async()=>{if(!data)return;setBusy(true);try{await api.request({method:data.isFollowing?'DELETE':'POST',url:'/designers/'+data.profile._id+'/follow'});await load()}finally{setBusy(false)}}
 const like=async(d:Design)=>{try{await api.request({method:d.isLiked?'DELETE':'POST',url:'/designers/'+d._id+'/like'});await load()}catch{setError('Đăng nhập để thích thiết kế.')}}
 const collectionAction=async(c?:Collection)=>{if(!c){const n=window.prompt('Tên collection mới')?.trim();if(n)await api.post('/designers/me/collections',{name:n})}else{const n=window.prompt('Tên mới hoặc DELETE để xóa: '+c.name);if(n?.toUpperCase()==='DELETE')await api.delete('/designers/me/collections/'+c._id);else if(n?.trim())await api.patch('/designers/me/collections/'+c._id,{name:n.trim()})}await load()}
 const publishDesign=async(d:Design)=>{const r=await api.post<any>('/designers/me/designs/'+d._id+'/publish');setStatus(r.data.data.design.status);await load()}
 const duplicateDesign=async(d:Design)=>{await api.post('/designers/me/designs/'+d._id+'/duplicate');setStatus('DRAFT');await load()}
 const editDesign=async(d:Design)=>{const n=window.prompt('Đổi tên thiết kế:',d.name);if(n?.trim()&&n!==d.name){await api.patch('/designers/me/designs/'+d._id,{name:n.trim()});await load()}}
 const deleteDesign=async(d:Design)=>{if(window.confirm('Bạn có chắc chắn muốn xóa thiết kế này?')){try{await api.delete('/designers/me/designs/'+d._id);setData(prev=>prev?{...prev,designs:prev.designs.filter(x=>x._id!==d._id)}:null);toast.success('Đã xóa thiết kế thành công')}catch(e:any){toast.error(e?.response?.data?.message||'Không thể xóa thiết kế')}}}
 if(error&&!data)return <div className="py-24 text-center">{error}</div>;if(!data)return <div className="py-24 text-center">Đang tải hồ sơ…</div>
 const p=data.profile
 return <div className="mx-auto max-w-7xl px-5 pb-20">
  <div className="h-48 overflow-hidden bg-neutral-100 sm:h-72">{p.coverImage&&<img src={p.coverImage} alt="" className="h-full w-full object-cover"/>}</div>
  <section className="mx-auto -mt-14 flex max-w-4xl flex-col items-center text-center sm:-mt-20"><img src={p.avatar||'/favicon.svg'} alt="" className="h-28 w-28 rounded-full border-4 border-white bg-white object-cover"/><h1 className="mt-4 font-heading text-3xl uppercase">{p.displayName}</h1><p className="mt-2 text-sm text-neutral-500">{data.followersCount} người theo dõi · {data.followingCount} đang theo dõi</p>{p.bio&&<p className="mt-4 max-w-2xl whitespace-pre-wrap">{p.bio}</p>}{data.owner?<button className="mt-5 border px-5 py-2 text-sm" onClick={()=>{setForm({username:p.username,displayName:p.displayName,bio:p.bio||'',avatar:p.avatar||'',coverImage:p.coverImage||''});setEditOpen(true)}}>Edit Profile</button>:user&&<button disabled={busy} className="mt-5 bg-black px-6 py-2 text-sm text-white" onClick={()=>void follow()}>{data.isFollowing?'Đang theo dõi':'Theo dõi'}</button>}</section>
  {data.owner&&summary&&<section className="mx-auto mt-10 grid max-w-4xl grid-cols-2 gap-4 border-y py-5 text-center sm:grid-cols-3"><div>Designs <b className="block">{summary.totalDesigns}</b></div><div>Published <b className="block">{summary.publishedDesigns}</b></div><div>Paid sales <b className="block">{summary.totalSales}</b></div><div>Gross sales <b className="block">{summary.grossSales.toLocaleString('vi-VN')} ₫</b></div><div>Platform fee <b className="block">{summary.commissionConfigured ? summary.platformFee?.toLocaleString('vi-VN') + " ₫" : "—"}</b></div><div>Designer earnings <b className="block">{summary.commissionConfigured ? summary.designerEarnings?.toLocaleString('vi-VN') + " ₫" : "—"}</b></div></section>}
  {editOpen&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form className="w-full max-w-lg space-y-3 bg-white p-6" onSubmit={e=>{e.preventDefault();void save()}}><h2 className="text-xl font-semibold">Edit designer profile</h2>{(['displayName','username','bio','avatar','coverImage'] as const).map(k=>k==='bio'?<textarea key={k} value={form[k]} placeholder="Bio" maxLength={1000} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full border p-3"/>:<input key={k} value={form[k]} placeholder={k} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full border p-3"/>)}<div className="flex justify-end gap-3"><button type="button" className="border px-4 py-2" onClick={()=>setEditOpen(false)}>Cancel</button><button disabled={busy} className="bg-black px-4 py-2 text-white">Save</button></div></form></div>}
  <section className="mt-14"><div className="flex flex-wrap items-end justify-between gap-4 border-b pb-4"><div><p className="text-xs uppercase tracking-widest text-neutral-500">Portfolio</p><h2 className="font-heading text-2xl uppercase">Designs</h2></div><div className="flex flex-wrap gap-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm thiết kế" className="border-b px-2 py-2"/><select value={category} onChange={e=>setCategory(e.target.value)} className="border-b py-2"><option value="">All categories</option>{[...new Set(data.designs.map(d=>d.category).filter(Boolean))].map(c=><option key={c} value={c}>{c}</option>)}</select><input type="number" min="0" value={minPrice} onChange={e=>{setPage(1);setMinPrice(e.target.value)}} placeholder="Min price" className="w-24 border-b px-2 py-2"/><input type="number" min="0" value={maxPrice} onChange={e=>{setPage(1);setMaxPrice(e.target.value)}} placeholder="Max price" className="w-24 border-b px-2 py-2"/><select value={sort} onChange={e=>setSort(e.target.value)} className="border-b py-2"><option>Newest</option><option>Popular</option><option>Best Selling</option><option>Price Low → High</option><option>Price High → Low</option></select><select value={collection} onChange={e=>setCollection(e.target.value)} className="border-b py-2"><option value="">All collections</option>{data.collections.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></div></div>
   {data.owner&&<div className="flex flex-wrap gap-3 py-4">{statusList.map(s=><button key={s} onClick={()=>setStatus(s)} className={status===s?'border-b border-black font-semibold':'text-neutral-500'}>{s.replace('_',' ')}</button>)}<button className="ml-auto underline" onClick={()=>void collectionAction()}>Create collection</button>{data.collections.map(c=><button key={c._id} className="text-xs underline" onClick={()=>void collectionAction(c)}>Manage {c.name}</button>)}</div>}
   {data.collections.length>0&&<div className="flex flex-wrap gap-3 py-3">{data.collections.map(c=><span key={c._id} className="text-xs uppercase tracking-widest">{c.name}</span>)}</div>}
   {data.designs.length===0?<p className="py-20 text-center text-neutral-500">No designs yet.</p>:<div className="grid grid-cols-2 gap-4 pt-6 md:grid-cols-3 lg:grid-cols-4">{data.designs.map(d=><article key={d._id}><Link to={d.status==='PUBLISHED'?'/design/'+d.slug:'#'}><div className="relative aspect-[4/5] bg-neutral-100"><img loading="lazy" src={d.thumbnail} alt={d.name} className="h-full w-full object-cover"/>{d.status!=='PUBLISHED'&&<span className="absolute left-2 top-2 bg-white px-2 py-1 text-[10px]">{d.status.replace('_',' ')}</span>}</div></Link><div className="mt-3 flex justify-between"><div><h3 className="text-sm font-medium uppercase">{d.name}</h3><p className="text-sm text-neutral-600">{d.price.toLocaleString('vi-VN')} ₫</p>{d.rejectionReason&&<p className="text-xs text-red-600">{d.rejectionReason}</p>}</div><button onClick={()=>void like(d)} aria-label="Like design">{d.isLiked?'♥':'♡'} {d.likesCount}</button></div>{data.owner&&<div className="mt-2 flex items-center justify-between gap-3 text-xs"><div className="flex items-center gap-3">{d.status==='PUBLISHED'?<button className="underline" onClick={()=>void duplicateDesign(d)}>Duplicate</button>:<button className="underline" onClick={()=>void editDesign(d)}>Rename</button>}<select aria-label='Collection' value={d.collectionId||''} onChange={async e=>{await api.patch('/designers/me/designs/'+d._id,{collectionId:e.target.value||null});await load()}} className='border-b bg-transparent'><option value=''>No collection</option>{data.collections.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select>{d.status==='PUBLISHED'&&<button className="underline" onClick={async()=>{await api.post('/designers/me/designs/'+d._id+'/unpublish');setStatus('DRAFT');await load()}}>Unpublish</button>}{['DRAFT','REJECTED'].includes(d.status)&&<button className="underline font-semibold" onClick={()=>void publishDesign(d)}>Publish</button>}</div><button className="text-red-500 hover:text-red-700" onClick={()=>void deleteDesign(d)} aria-label="Xóa thiết kế"><Trash2 size={14}/></button></div>}</article>)}</div>}
   {data.pagination.totalPages>1&&<nav className="mt-10 flex justify-center gap-4"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="border px-3 py-2 disabled:opacity-40">Previous</button><span className="py-2">{page} / {data.pagination.totalPages}</span><button disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)} className="border px-3 py-2 disabled:opacity-40">Next</button></nav>}
  </section>
 </div>
}








