const svgThumbnail = (background, headline, accent) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 440"><rect width="360" height="440" fill="${background}"/><path d="M90 95 135 75h90l45 20 55 50-42 55-35-25v190H112V175l-35 25-42-55z" fill="#f4f1eb" stroke="#d5d0c7" stroke-width="4"/><text x="180" y="235" text-anchor="middle" font-family="Arial,sans-serif" font-size="${headline.length > 12 ? 23 : 31}" font-weight="800" letter-spacing="2" fill="${accent}">${headline}</text><path d="M135 252h90" stroke="${accent}" stroke-width="3"/></svg>`)}`;
const text = (id, name, value, options = {}) => ({
  id, type: 'text', name, visible: true, locked: false, zIndex: options.zIndex ?? 1,
  text: value, fontFamily: options.fontFamily ?? 'Montserrat', fontSize: options.fontSize ?? 28,
  fontWeight: options.fontWeight ?? 700, italic: false, underline: false, textTransform: 'uppercase',
  align: 'center', color: options.color ?? '#111111', stroke: '#ffffff', strokeWidth: 0, opacity: 1,
  x: options.x ?? 50, y: options.y ?? 47, rotation: options.rotation ?? 0, scaleX: 1, scaleY: 1, effect: 'Straight',
});

module.exports = [
  { slug: 'minimal-form', name: 'Minimal Form', category: 'Minimal', style: 'Minimal', tags: ['clean', 'typography', 'essential'], description: 'A clean, centered wordmark with a quiet editorial feel.', thumbnail: svgThumbnail('#e9e5dc', 'FORM', '#252525'), frontDesign: { layers: [text('minimal-form-title', 'Form', 'FORM', { fontSize: 32 })] }, backDesign: { layers: [] } },
  { slug: 'city-runner', name: 'City Runner', category: 'Sport', style: 'Streetwear', tags: ['sport', 'running', 'city'], description: 'Bold athletic lettering for everyday movement.', thumbnail: svgThumbnail('#c9d9d3', 'RUN CLUB', '#173d35'), frontDesign: { layers: [text('city-runner-title', 'Run Club', 'RUN CLUB', { fontSize: 24, color: '#173d35' }), text('city-runner-year', 'Est 2024', 'EST. 2024', { fontSize: 11, y: 55, color: '#173d35' })] }, backDesign: { layers: [text('city-runner-back', 'City Runner Back', 'CITY RUNNER', { fontSize: 19, y: 35, color: '#173d35' })] } },
  { slug: 'retro-sunset', name: 'Retro Sunset', category: 'Vintage', style: 'Vintage', tags: ['retro', 'sunset', 'summer'], description: 'Warm retro typography inspired by vintage travel prints.', thumbnail: svgThumbnail('#ead1b4', 'SUNSET', '#a84b35'), frontDesign: { layers: [text('retro-sunset-title', 'Sunset', 'SUNSET', { fontFamily: 'Bebas Neue', fontSize: 34, color: '#a84b35', rotation: -5 }), text('retro-sunset-caption', 'California', 'CALIFORNIA', { fontSize: 11, y: 55, color: '#a84b35' })] }, backDesign: { layers: [] } },
  { slug: 'manga-panel', name: 'Manga Panel', category: 'Anime', style: 'Graphic', tags: ['anime', 'manga', 'comic'], description: 'A graphic comic inspired layout with editable title layers.', thumbnail: svgThumbnail('#ded9eb', 'MANGA', '#47336c'), frontDesign: { layers: [text('manga-panel-title', 'Manga', 'MANGA', { fontFamily: 'Bebas Neue', fontSize: 34, color: '#47336c', rotation: -4 }), text('manga-panel-caption', 'Volume 01', 'VOL. 01', { fontSize: 12, y: 54, color: '#47336c' })] }, backDesign: { layers: [text('manga-panel-back', 'Manga back', 'STORY IN MOTION', { fontSize: 14, y: 40, color: '#47336c' })] } },
  { slug: 'abstract-motion', name: 'Abstract Motion', category: 'Abstract', style: 'Graphic', tags: ['abstract', 'motion', 'art'], description: 'Layered expressive type with an energetic diagonal composition.', thumbnail: svgThumbnail('#d7d8de', 'MOVE', '#ba452e'), frontDesign: { layers: [text('abstract-motion-shadow', 'Move shadow', 'MOVE', { fontSize: 32, color: '#ba452e', x: 47, y: 49, rotation: -8 }), text('abstract-motion-title', 'Move', 'MOVE', { fontSize: 28, color: '#242834', x: 51, y: 46, rotation: -8, zIndex: 2 })] }, backDesign: { layers: [] } },
  { slug: 'type-study', name: 'Type Study', category: 'Typography', style: 'Minimal', tags: ['typography', 'type', 'lettering'], description: 'A simple typographic study built from individually editable text.', thumbnail: svgThumbnail('#eee8df', 'TYPE 01', '#382f29'), frontDesign: { layers: [text('type-study-title', 'Type 01', 'TYPE 01', { fontFamily: 'Bebas Neue', fontSize: 34, color: '#382f29' }), text('type-study-caption', 'Letterform series', 'LETTERFORM SERIES', { fontSize: 9, y: 55, color: '#382f29' })] }, backDesign: { layers: [] } },
  { slug: 'block-party', name: 'Block Party', category: 'Streetwear', style: 'Streetwear', tags: ['streetwear', 'bold', 'graphic'], description: 'Stacked streetwear typography for a strong front print.', thumbnail: svgThumbnail('#e2c5bf', 'BLOCK', '#9a2c28'), frontDesign: { layers: [text('block-party-title', 'Block', 'BLOCK', { fontFamily: 'Bebas Neue', fontSize: 36, color: '#9a2c28', rotation: -3 }), text('block-party-caption', 'Party', 'PARTY', { fontFamily: 'Bebas Neue', fontSize: 20, color: '#202020', y: 55, rotation: -3 })] }, backDesign: { layers: [] } },
  { slug: 'graphic-orbit', name: 'Graphic Orbit', category: 'Graphic', style: 'Abstract', tags: ['graphic', 'orbit', 'space'], description: 'A compact graphic title composition with two editable elements.', thumbnail: svgThumbnail('#cad5e2', 'ORBIT', '#22466f'), frontDesign: { layers: [text('graphic-orbit-title', 'Orbit', 'ORBIT', { fontSize: 28, color: '#22466f' }), text('graphic-orbit-caption', 'Beyond limits', 'BEYOND LIMITS', { fontSize: 9, y: 54, color: '#22466f' })] }, backDesign: { layers: [text('graphic-orbit-back', 'Orbit back', 'EXPLORE MORE', { fontSize: 12, y: 38, color: '#22466f' })] } },
];
