const products = [
  {
    name: 'Ao Boxy Heavy Tee Black',
    slug: 'ao-boxy-heavy-tee-black',
    description: 'Ao boxy cotton day 280gsm, form vuong vuc chuan streetwear. Co tron, tay lo, chat vai day dan khong bai gian sau nhieu lan giat.',
    category: 'T-Shirt',
    style: 'Boxy',
    fit: 'Boxy',
    material: 'Heavy Cotton 280gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 349000,
    discountPrice: 319000,
    imageUrl: 'https://picsum.photos/seed/boxy1/400/500',
    images: ['https://picsum.photos/seed/boxy1/400/500', 'https://picsum.photos/seed/boxy1b/400/500'],
    colors: [
      { name: 'Den', hex: '#111111', stock: 30 },
      { name: 'Trang', hex: '#F5F5F5', stock: 20 },
      { name: 'Be', hex: '#D4B896', stock: 15 },
    ],
    sizes: [
      { label: 'S', stock: 10, measurements: { chest: 108, length: 68, shoulder: 48 } },
      { label: 'M', stock: 20, measurements: { chest: 114, length: 70, shoulder: 50 } },
      { label: 'L', stock: 25, measurements: { chest: 120, length: 72, shoulder: 52 } },
      { label: 'XL', stock: 10, measurements: { chest: 126, length: 74, shoulder: 54 } },
    ],
    stock: 65,
    tags: ['streetwear', 'boxy', 'heavy cotton', 'basic', 'unisex'],
    rating: 4.8,
    sold: 75,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Ao Boxy Heavy Tee White',
    slug: 'ao-boxy-heavy-tee-white',
    description: 'Phien ban mau trang cua dong Boxy Heavy Tee. Cotton 280gsm, form boxy rong thoai mai, thich hop in custom hoac mac basic.',
    category: 'T-Shirt',
    style: 'Boxy',
    fit: 'Boxy',
    material: 'Heavy Cotton 280gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 349000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/boxy2/400/500',
    images: ['https://picsum.photos/seed/boxy2/400/500'],
    colors: [
      { name: 'Trang', hex: '#F5F5F5', stock: 25 },
      { name: 'Kem', hex: '#FFFDD0', stock: 20 },
    ],
    sizes: [
      { label: 'S', stock: 8, measurements: { chest: 108, length: 68, shoulder: 48 } },
      { label: 'M', stock: 18, measurements: { chest: 114, length: 70, shoulder: 50 } },
      { label: 'L', stock: 12, measurements: { chest: 120, length: 72, shoulder: 52 } },
      { label: 'XL', stock: 7, measurements: { chest: 126, length: 74, shoulder: 54 } },
    ],
    stock: 45,
    tags: ['streetwear', 'boxy', 'heavy cotton', 'trang', 'basic'],
    rating: 4.7,
    sold: 50,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Ao Thun Oversize Basic Black',
    slug: 'ao-thun-oversize-basic-black',
    description: 'Ao thun oversize form rong, chat lieu cotton 100%, phong cach streetwear toi gian. Co tron, tay lo, phu hop mac hang ngay.',
    category: 'T-Shirt',
    style: 'Oversize',
    fit: 'Oversized',
    material: '100% Cotton 220gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 299000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/shirt1/400/500',
    images: ['https://picsum.photos/seed/shirt1/400/500'],
    colors: [{ name: 'Den', hex: '#111111', stock: 30 }],
    sizes: [
      { label: 'S', stock: 8, measurements: { chest: 112, length: 70, shoulder: 50 } },
      { label: 'M', stock: 15, measurements: { chest: 118, length: 72, shoulder: 52 } },
      { label: 'L', stock: 20, measurements: { chest: 124, length: 74, shoulder: 54 } },
      { label: 'XL', stock: 7, measurements: { chest: 130, length: 76, shoulder: 56 } },
    ],
    stock: 50,
    tags: ['oversize', 'basic', 'streetwear', 'minimalist', 'den'],
    rating: 4.6,
    sold: 120,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Ao Thun Oversize Basic White',
    slug: 'ao-thun-oversize-basic-white',
    description: 'Ao thun oversize mau trang, chat lieu cotton 100%, phu hop mac hang ngay. De phoi voi moi loai quan.',
    category: 'T-Shirt',
    style: 'Oversize',
    fit: 'Oversized',
    material: '100% Cotton 220gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 299000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/shirt3/400/500',
    images: ['https://picsum.photos/seed/shirt3/400/500'],
    colors: [
      { name: 'Trang', hex: '#F5F5F5', stock: 35 },
      { name: 'Xam nhat', hex: '#D1D5DB', stock: 25 },
    ],
    sizes: [
      { label: 'S', stock: 10, measurements: { chest: 112, length: 70, shoulder: 50 } },
      { label: 'M', stock: 20, measurements: { chest: 118, length: 72, shoulder: 52 } },
      { label: 'L', stock: 20, measurements: { chest: 124, length: 74, shoulder: 54 } },
      { label: 'XL', stock: 10, measurements: { chest: 130, length: 76, shoulder: 56 } },
    ],
    stock: 60,
    tags: ['oversize', 'basic', 'minimalist', 'trang', 'summer'],
    rating: 4.5,
    sold: 95,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Ao Boxy Heavy Cream',
    slug: 'ao-boxy-heavy-cream',
    description: 'Ao boxy mau kem, chat lieu cotton cao cap 280gsm, de phoi do. Tone mau trung tinh phu hop moi phong cach.',
    category: 'T-Shirt',
    style: 'Boxy',
    fit: 'Boxy',
    material: 'Heavy Cotton 280gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 359000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/shirt5/400/500',
    images: ['https://picsum.photos/seed/shirt5/400/500'],
    colors: [
      { name: 'Kem', hex: '#FFFDD0', stock: 20 },
      { name: 'Be', hex: '#D4B896', stock: 15 },
    ],
    sizes: [
      { label: 'S', stock: 8, measurements: { chest: 108, length: 68, shoulder: 48 } },
      { label: 'M', stock: 15, measurements: { chest: 114, length: 70, shoulder: 50 } },
      { label: 'L', stock: 10, measurements: { chest: 120, length: 72, shoulder: 52 } },
      { label: 'XL', stock: 2, measurements: { chest: 126, length: 74, shoulder: 54 } },
    ],
    stock: 35,
    tags: ['boxy', 'kem', 'be', 'neutral', 'minimalist', 'elegant'],
    rating: 4.7,
    sold: 60,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Ao Graphic Tee Street',
    slug: 'ao-graphic-tee-street',
    description: 'Ao thun graphic in hoa tiet streetwear, form unisex tre trung. Chat lieu cotton mem mai, in DTG ben mau.',
    category: 'T-Shirt',
    style: 'Regular',
    fit: 'Regular',
    material: '100% Cotton 200gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 329000,
    discountPrice: 299000,
    imageUrl: 'https://picsum.photos/seed/shirt7/400/500',
    images: ['https://picsum.photos/seed/shirt7/400/500'],
    colors: [
      { name: 'Den', hex: '#111111', stock: 30 },
      { name: 'Trang', hex: '#F5F5F5', stock: 25 },
    ],
    sizes: [
      { label: 'S', stock: 10, measurements: { chest: 104, length: 66, shoulder: 46 } },
      { label: 'M', stock: 20, measurements: { chest: 110, length: 68, shoulder: 48 } },
      { label: 'L', stock: 18, measurements: { chest: 116, length: 70, shoulder: 50 } },
      { label: 'XL', stock: 7, measurements: { chest: 122, length: 72, shoulder: 52 } },
    ],
    stock: 55,
    tags: ['graphic', 'streetwear', 'in', 'printed', 'bold'],
    rating: 4.6,
    sold: 80,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Ao Graphic Logo Altera',
    slug: 'ao-graphic-logo-altera',
    description: 'Ao thun in logo Altera noi bat, form unisex, phu hop mac hang ngay. Cotton 220gsm, in cao tan ben dep.',
    category: 'T-Shirt',
    style: 'Regular',
    fit: 'Regular',
    material: '100% Cotton 220gsm',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 349000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/shirt2/400/500',
    images: ['https://picsum.photos/seed/shirt2/400/500'],
    colors: [
      { name: 'Den', hex: '#111111', stock: 20 },
      { name: 'Navy', hex: '#1E3A5F', stock: 15 },
      { name: 'Trang', hex: '#F5F5F5', stock: 15 },
    ],
    sizes: [
      { label: 'S', stock: 10, measurements: { chest: 104, length: 66, shoulder: 46 } },
      { label: 'M', stock: 20, measurements: { chest: 110, length: 68, shoulder: 48 } },
      { label: 'L', stock: 15, measurements: { chest: 116, length: 70, shoulder: 50 } },
      { label: 'XL', stock: 5, measurements: { chest: 122, length: 72, shoulder: 52 } },
    ],
    stock: 50,
    tags: ['altera', 'logo', 'graphic', 'brand', 'streetwear'],
    rating: 4.9,
    sold: 110,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Ao Baby Tee Crop White',
    slug: 'ao-baby-tee-crop-white',
    description: 'Ao baby tee form crop ngan, co tron, tay ngan. Chat cotton mem min, phong cach Y2K/Korean cute.',
    category: 'T-Shirt',
    style: 'Baby Tee',
    fit: 'Slim',
    material: '100% Cotton 180gsm',
    brand: 'ALTERA',
    gender: 'Women',
    price: 279000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/baby1/400/500',
    images: ['https://picsum.photos/seed/baby1/400/500'],
    colors: [
      { name: 'Trang', hex: '#F5F5F5', stock: 25 },
      { name: 'Hong nhat', hex: '#FBCFE8', stock: 20 },
      { name: 'Xanh nhat', hex: '#BAE6FD', stock: 15 },
    ],
    sizes: [
      { label: 'XS', stock: 10, measurements: { chest: 84, length: 46, shoulder: 36 } },
      { label: 'S', stock: 25, measurements: { chest: 88, length: 48, shoulder: 38 } },
      { label: 'M', stock: 20, measurements: { chest: 92, length: 50, shoulder: 40 } },
      { label: 'L', stock: 5, measurements: { chest: 96, length: 52, shoulder: 42 } },
    ],
    stock: 60,
    tags: ['baby tee', 'crop', 'y2k', 'korean', 'cute', 'nu', 'women'],
    rating: 4.8,
    sold: 90,
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Mu Bucket Hat Black',
    slug: 'mu-bucket-hat-black',
    description: 'Mu bucket hat mau den, chong nang tot, phong cach tre trung. Chat lieu canvas ben chac.',
    category: 'Accessory',
    style: null,
    fit: null,
    material: 'Canvas',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 220000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/hat1/400/500',
    images: ['https://picsum.photos/seed/hat1/400/500'],
    colors: [
      { name: 'Den', hex: '#111111', stock: 25 },
      { name: 'Be', hex: '#D4B896', stock: 20 },
    ],
    sizes: [{ label: 'FREESIZE', stock: 45, measurements: {} }],
    stock: 45,
    tags: ['mu', 'bucket hat', 'streetwear', 'chong nang', 'summer'],
    rating: 4.7,
    sold: 45,
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Tui Tote Canvas Altera',
    slug: 'tui-tote-canvas-altera',
    description: 'Tui tote vai canvas in logo Altera, dung duoc nhieu do, unisex. Quai vai chac chan, dung tich lon.',
    category: 'Accessory',
    style: null,
    fit: null,
    material: 'Canvas',
    brand: 'ALTERA',
    gender: 'Unisex',
    price: 199000,
    discountPrice: null,
    imageUrl: 'https://picsum.photos/seed/bag1/400/500',
    images: ['https://picsum.photos/seed/bag1/400/500'],
    colors: [
      { name: 'Trang', hex: '#F5F5F5', stock: 35 },
      { name: 'Den', hex: '#111111', stock: 25 },
    ],
    sizes: [{ label: 'FREESIZE', stock: 60, measurements: {} }],
    stock: 60,
    tags: ['tui', 'tote', 'canvas', 'altera', 'unisex', 'di hoc'],
    rating: 4.6,
    sold: 60,
    isFeatured: false,
    isActive: true,
  },
];

module.exports = products;
